"""mode_choice_logit.py — Contract and evaluator of the second oracle (multinomial logit).

This module cannot *estimate* a logit: it can **read it back and make it predict**. The
split is deliberate — estimation needs scikit-learn, prediction needs only
numpy, and prediction is what runs in the consumers (summary page, experiment
decision-maker, `controller` container).

**Why an artefact of coefficients and not a serialised model.** A scikit-learn
`pickle` goes stale at the library's next version and cannot be read in a
diff. A multinomial logit is only `softmax(Zβ + α)`: the coefficients, the per-alternative
intercepts and the construction contract of `Z` are enough, can be read and checked by
hand: the artefact is self-contained in the same sense as the booster's. It is not versioned
for all that — `scripts/progedo_logit/*.json` is gitignored, except `feature_spec.json` — and is
regenerated by `make logit`.

**The design matrix, and the only trap of this module.** The input is not the raw row:
it is the matrix **already encoded by the same `encode_features` as the booster** (category →
integer code of the spec, boolean → 0/1, numeric → float, missing → NaN). This is what makes
information parity true by construction: the two oracles see exactly the same
values, and only one encoding function exists. This module only **expands** that
matrix into indicators, standardises the numerics and materialises the missing values.

**Missing values, declared rather than endured.** The booster routes NaN natively; a logit
cannot. Three rules, written in the artefact and applied here:

- missing or out-of-spec categorical → category `__missing__` (never the modal category);
- missing boolean → 0, **plus** its missing indicator at 1;
- missing numeric → the weighted train mean (i.e. 0 after centring), **plus** its
  missing indicator at 1.

The indicators are what distinguishes "absent" from "average": without them, imputation
would assert a value the data does not carry.
"""

from __future__ import annotations

from typing import Any

import numpy as np

# Format of the second oracle's artefact. Describes the *structure* of the JSON, independently of
# `spec_version`, which describes the variable contract. A consumer must refuse a format
# it does not know rather than interpreting its keys at random.
LOGIT_FORMAT = "mnl_mode_choice_policy"
LOGIT_FORMAT_VERSION = 1

#: Explicit fallback category for an absent or out-of-spec categorical.
MISSING_CATEGORY = "__missing__"


def design_columns(spec: dict, missing_indicators: list[str]) -> list[str]:
    """Columns of the design matrix, in an order **imposed by the spec**.

    A categorical with *n* categories gives *n − 1* indicators: the spec's first
    category is the **reference** (its effect is absorbed by the intercept). Without a reference
    left out, the matrix is singular and the coefficients can no longer be interpreted one by
    one, even if regularisation keeps the estimation from failing.
    """
    columns: list[str] = []
    for feature in spec["features"]:
        name, kind = feature["name"], feature["kind"]
        if kind == "categorical":
            modalities = list(feature["categories"]) + [MISSING_CATEGORY]
            columns += [f"{name}={m}" for m in modalities[1:]]
        else:
            columns.append(name)
        if name in missing_indicators:
            columns.append(f"{name}__missing")
    return columns


def design_matrix(encoded: Any, artefact: dict) -> np.ndarray:
    """Design matrix `Z`, from the booster's encoded matrix.

    ``encoded`` is a ``DataFrame`` with one column per spec variable, in the spec
    order — the output of ``fit_mode_choice_policy.encode_features``. No column is
    inferred from the values present: everything comes from the artefact, otherwise two
    prediction batches would produce two different matrices.

    Reads the contract under the artefact's ``logit`` key; another family goes through
    :func:`design_matrix_from_contract` with the contract it carries, without having to file
    its block under a family name that would not be its own.
    """
    return design_matrix_from_contract(encoded, artefact["features"], artefact["logit"])


def design_matrix_from_contract(encoded: Any, features: list[dict],
                                contract: dict) -> np.ndarray:
    """Design matrix, from a bare contract — the core shared between families.

    **Why this function is public.** The kernel logistic regression of
    ticket 043 requires exactly this matrix: an RBF kernel only makes sense on
    standardised variables, and missing values are materialised there by the same
    indicators. Redoing the encoding in the third family would have produced a shift
    that nothing would have flagged — the probabilities would have stayed perfectly plausible.
    A single function therefore builds `Z` for all families, and the contract
    (columns, indicators, standardisation, reference categories) travels with
    the artefact that fixed it.
    """
    stats = contract["standardization"]
    indicators = set(contract["missing_indicators"])
    n = len(encoded)
    blocks: dict[str, np.ndarray] = {}

    for feature in features:
        name, kind = feature["name"], feature["kind"]
        values = np.asarray(encoded[name], dtype="float64")
        missing = np.isnan(values)
        if kind == "categorical":
            modalities = list(feature["categories"]) + [MISSING_CATEGORY]
            codes = np.where(missing, len(modalities) - 1, values).astype("int64")
            # An out-of-spec category is already NaN at encoding; an out-of-range code can
            # therefore only come from an artefact inconsistent with its spec.
            if codes.min() < 0 or codes.max() >= len(modalities):
                raise ValueError(
                    f"Modality code out of bounds for {name}: "
                    f"{codes.min()}..{codes.max()} for {len(modalities)} modalities.")
            for index, modality in enumerate(modalities):
                if index == 0:
                    continue                      # reference category
                blocks[f"{name}={modality}"] = (codes == index).astype("float64")
        else:
            column = np.where(missing, 0.0, values)
            if name in stats:
                mean, std = stats[name]["mean"], stats[name]["std"]
                column = np.where(missing, 0.0, (column - mean) / std)
            blocks[name] = column
        if name in indicators:
            blocks[f"{name}__missing"] = missing.astype("float64")

    order = contract["design_columns"]
    unknown = [c for c in order if c not in blocks]
    if unknown:
        raise ValueError(f"Colonnes de dessin introuvables : {unknown[:5]}")
    matrix = np.empty((n, len(order)), dtype="float64")
    for position, column in enumerate(order):
        matrix[:, position] = blocks[column]
    return matrix


def softmax(scores: np.ndarray) -> np.ndarray:
    """Row-wise softmax, stabilised by subtracting the maximum."""
    shifted = scores - scores.max(axis=1, keepdims=True)
    exponentials = np.exp(shifted)
    return exponentials / exponentials.sum(axis=1, keepdims=True)


class LogitPredictor:
    """Multinomial logit evaluator, without scikit-learn.

    Deliberately exposes the same surface as the LightGBM booster (``predict``,
    ``feature_name``): the consumers of the common set then call **the same prediction
    path** for both oracles, which is the condition for their two parquets
    to be comparable (rule R7 of `specs/score_composite_deux_oracles.md`).
    """

    def __init__(self, artefact: dict):
        self.artefact = artefact
        logit = artefact["logit"]
        self.coef = np.asarray(logit["coef"], dtype="float64")
        self.intercept = np.asarray(logit["intercept"], dtype="float64")
        self.classes = list(artefact["target"]["classes"])
        self.names = [f["name"] for f in artefact["features"]]
        expected = len(logit["design_columns"])
        if self.coef.shape != (len(self.classes), expected):
            raise ValueError(
                f"Coefficients de forme {self.coef.shape}, attendu "
                f"({len(self.classes)}, {expected}).")
        if self.intercept.shape != (len(self.classes),):
            raise ValueError(
                f"Intercepts of shape {self.intercept.shape}, expected ({len(self.classes)},).")

    # ``num_iteration`` has no meaning for a logit: accepted and ignored, so that
    # the caller does not have to know which oracle it holds.
    def predict(self, matrix: Any, num_iteration: Any = None) -> np.ndarray:
        """Probabilities over the four classes, in the spec order."""
        design = design_matrix(matrix, self.artefact)
        return softmax(design @ self.coef.T + self.intercept)

    def feature_name(self) -> list[str]:
        """Expected variables, in the spec order — same contract as the booster."""
        return list(self.names)
