#!/usr/bin/env python3
"""Figure — break and return of the decided car, around an injected shock (ticket 106).

WHAT THE FIGURE PLOTS: per day relative to the shock, the decisions where the car was offered
AND where the model made the call, split between "car chosen" and "another mode".

WHY "DECIDED" AND NOT THE RAW SHARE
------------------------------------------
The raw share counts as decisions what the vehicle chain imposes. On the run of
2026-09-23, `sortie_bloquee` goes from 8 trips before the shock to 39 after: having left
without the car in the morning, the agent cannot take it back for the rest of the day, and
this propagation then reads as a repeated giving-up. A decision only enters here if the car
was AMONG the offered modes AND if `Méthode de sélection == LLM` — trips with a single
itinerary drop out, including those where the car was the only choice. On this run, the car
share goes from 72.2 % to 23.2 % raw, and from 97.2 % to 33.3 % decided: the two numbers do
not tell the same story, and only the second speaks of choice.

WHAT THE FIGURE DOES NOT PLOT, AND WHY — measured on 2026-09-24, to be kept
----------------------------------------------------------------------------
A second curve was planned: "is the memory still cited in the reasoning?",
to separate two explanations of a return to the car — the memory has faded, or it is
there and no longer governs. It was REMOVED for lack of a reliable instrument. Three lexicons
tried on the run `2026-09-23_20_35`, all with the witness machinery (distinctive words,
calibrated exclusion list, two-word threshold):

  * the words of the INJECTED TEXT (23 words) → almost no marked reasoning, before or after.
    The reasoning paraphrases: it says "car breakdown" where the text says "the engine
    stalled on the expressway". No distinctive word survives the paraphrase.
  * the words of the 31 LONG-TERM MEMORY entries carrying the shock (407 words) → 56 reasonings
    marked out of 77 BEFORE the shock. The vocabulary of a reflection is that of an ordinary
    day; it marks everything.
  * the labels of the CONCEPT generated by the agent ("engine stall, expressway, breakdown,
    roadside assistance") → 6/77 before, 38/101 after. The separation exists but stays dirty
    on both sides: `short`, `distance`, `speed`, `shop` mark ordinary days, and
    a reasoning that only says "car breakdown" falls below the two-word threshold.

WHAT THIS TEACHES ABOUT THE WITNESS: its exclusion list is calibrated on CONSOLIDATION
REFLECTIONS, and it does not transfer to a decision reasoning. The witness stays valid
where it is plugged in — it compares a consolidation with the text that has just fed it, two
texts of the same register. Extending it to reasoning would need its own calibration, and that
is not this ticket. For now, the persistence of the memory in decisions is read from
the verbatims, recorded in `$PAPER_DIR/article-court/experiments_results.md` (papers repository).

VACUITY GUARD, NOT NEGOTIABLE
---------------------------------
No mean is plotted: each relative day is a COLUMN whose height is the
number of decisions behind it. A day with one decision cannot look like a day with
eight. In this repository, the absence of measurement readily produces the perfect value, and
this pattern has lied before. The script refuses to compose below `DECISIONS_MINIMALES` in total.

Standard library only, inline SVG, modelled on `figure_fenetre_choc.py`.
Figure composed in ENGLISH: all of the paper's figures are.

    python scripts/analysis/figure_rupture_retour.py <run> -o <sortie.svg>
    python scripts/analysis/figure_rupture_retour.py <traité> --temoin <témoin> \
        --mode public_transport -o <sortie.svg>

`--mode` names the TRACKED mode, the one the event is supposed to drive away: `car` for a
car breakdown, `public_transport` for a transit outage. The mode is never guessed —
three mode vocabularies coexist in this repository (ticket 077, lot A), and a word passing
"by default" would plot another mode's curve without anything saying so.

`--temoin` stacks the control arm under the treated arm, on the same x axis. It is the only
reading that allows a conclusion: the c3 campaign of 2026-09-24 shows the two arms apart
by at most six points, that is no effect — and a figure of the treated arm alone would have
shown a curve going up and down, which could have been read as an effect.

The CSV of the plotted points is written next to the SVG, same name, `.csv` extension.
"""

from __future__ import annotations

import argparse
import csv
import datetime
import json
import sys
from pathlib import Path

RACINE = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(RACINE / "services" / "llm-agents"))

from llm.evenements import temoin  # noqa: E402  (après l'ajout au chemin)

# Validated categorical palette (dataviz, slots 1-2). Do not replace without revalidating:
#   node scripts/validate_palette.js "#2a78d6,#eb6834,#1baf7a" --mode light
SUIVI, AUTRE = "#eb6834", "#2a78d6"

# Canonical mode → label in `moves.csv`, and its English name for the figure. EXPLICIT and not
# guessed, modelled on `figure_evenement.py`.
MODES = {
    "walking": ("Marche", "walking"),
    "cycling": ("Vélo", "cycling"),
    "car": ("Voiture", "the car"),
    "public_transport": ("Transports_collectifs", "public transport"),
    "train": ("Train", "the train"),
    "motorbike": ("Deux-roues motorisé", "the motorbike"),
}

# Below this total, nothing is composed: a break figure drawn on a few decisions
# looks exactly like a break figure drawn on two hundred.
DECISIONS_MINIMALES = 20

L, R, T, B = 66, 26, 96, 86
W = 1180
CORPS = 210   # body height of a band (one arm)
ECART = 52    # space between two bands


def texte_injecte(run: Path) -> str:
    """Returns the identifier of the injected event, to name it on the figure.

    Several injections are possible; the first is named and the others are reported —
    the `Jour relatif au choc` x axis of `moves.csv` carries only one anyway.
    """
    chemin = run / "evenements.jsonl"
    if not chemin.is_file():
        raise SystemExit(f"❌ {chemin} not found — this run carries no injection")
    lignes = [json.loads(l) for l in chemin.read_text(encoding="utf-8").splitlines() if l.strip()]
    # Ticket 111: an informed member (`origine: entendu`) is not one more injection.
    lignes = [l for l in lignes if l.get("origine") != "entendu"]
    if not lignes:
        raise SystemExit(f"❌ {chemin} is empty — this run carries no injection")
    if len(lignes) > 1:
        print(f"  ⚠ {len(lignes)} injections in this run; the figure only names the first.")
    d = lignes[0]
    texte = d.get("texte") or d.get("vecu") or ""
    mots = temoin.mots_distinctifs(texte)
    print(f"  {len(mots)} distinctive word(s) in the injected text: {', '.join(mots[:8])}…")
    return d.get("choc_id") or d.get("evenement_id") or "?"


def lire(run: Path, libelle_mode: str) -> tuple[dict[int, list[int]], dict[int, int]]:
    """Returns `({jour: [tracked mode, other mode]}, {jour: decisions of the day, free or not})`."""
    chemin = run / "moves.csv"
    if not chemin.is_file():
        raise SystemExit(f"❌ {chemin} not found — this run has no decision log")

    choix: dict[int, list[int]] = {}
    tous: dict[int, int] = {}
    with chemin.open(encoding="utf-8") as f:
        lecteur = csv.DictReader(f)
        for colonne in ("Jour relatif au choc", "Modes proposés au LLM",
                        "Méthode de sélection", "Mode de transport Choisi"):
            if colonne not in (lecteur.fieldnames or []):
                raise SystemExit(f"❌ column \"{colonne}\" missing from {chemin} — "
                                 f"this moves.csv does not come from an event run")
        for ligne in lecteur:
            brut = (ligne["Jour relatif au choc"] or "").strip()
            if not brut:
                continue
            j = int(brut)
            tous[j] = tous.get(j, 0) + 1
            if libelle_mode not in ligne["Modes proposés au LLM"]:
                continue
            if ligne["Méthode de sélection"] != "LLM":
                continue
            c = choix.setdefault(j, [0, 0])
            c[0 if libelle_mode in ligne["Mode de transport Choisi"] else 1] += 1
    return choix, tous


def jours_relatifs(run: Path) -> dict[int, str]:
    """`{relative day: simulated date}` — carries the treated arm's x axis over to the control.

    The control arm receives no event: its `Jour relatif au choc` is empty, and that is
    expected. Both arms share the seeds and the same calendar, so the simulated date
    is enough to align them. Aligning on anything else — the row index, the arrival order —
    would shift the two curves against each other without anything saying so.
    """
    table: dict[int, str] = {}
    with (run / "moves.csv").open(encoding="utf-8") as f:
        for ligne in csv.DictReader(f):
            brut = (ligne["Jour relatif au choc"] or "").strip()
            if not brut:
                continue
            jour = datetime.datetime.fromtimestamp(
                int(float(ligne["Temps simulé"])), datetime.UTC
            ).strftime("%Y-%m-%d")
            table[int(brut)] = jour
    return table


def lire_temoin(run: Path, libelle_mode: str,
                calendrier: dict[int, str]) -> tuple[dict[int, list[int]], dict[int, int]]:
    """The control arm, reindexed on the relative days of the treated arm."""
    par_date = {date: rel for rel, date in calendrier.items()}
    choix: dict[int, list[int]] = {}
    tous: dict[int, int] = {}
    chemin = run / "moves.csv"
    if not chemin.is_file():
        raise SystemExit(f"❌ {chemin} not found — the control arm has no log")
    with chemin.open(encoding="utf-8") as f:
        for ligne in csv.DictReader(f):
            date = datetime.datetime.fromtimestamp(
                int(float(ligne["Temps simulé"])), datetime.UTC
            ).strftime("%Y-%m-%d")
            j = par_date.get(date)
            if j is None:
                continue
            tous[j] = tous.get(j, 0) + 1
            if libelle_mode not in ligne["Modes proposés au LLM"]:
                continue
            if ligne["Méthode de sélection"] != "LLM":
                continue
            c = choix.setdefault(j, [0, 0])
            c[0 if libelle_mode in ligne["Mode de transport Choisi"] else 1] += 1
    return choix, tous


def _x(j: int, jmin: int, jmax: int) -> float:
    return L + (j - jmin) / max(jmax - jmin, 1) * (W - L - R)


def _bande(a, choix: dict, jours: list[int], jmin: int, jmax: int, hmax: int,
           haut: float, corps: float, larg: float, titre: str) -> None:
    """One arm: one column per relative day, as tall as its number of decisions."""
    a(f'<text class="ink2" x="{L}" y="{haut - 10:.1f}" font-size="11.5">{titre}</text>')
    for n in range(0, hmax + 1, max(1, hmax // 3)):
        y = haut + corps - n / hmax * corps
        a(f'<line class="grid" x1="{L}" y1="{y:.1f}" x2="{W - R}" y2="{y:.1f}" stroke-width="1"/>')
        a(f'<text class="ink2" x="{L - 10}" y="{y + 4:.1f}" font-size="11" '
          f'text-anchor="end">{n}</text>')
    x0 = _x(0, jmin, jmax)
    a(f'<line x1="{x0:.1f}" y1="{haut - 6:.1f}" x2="{x0:.1f}" y2="{haut + corps:.1f}" '
      f'stroke="#5c5b54" stroke-width="1.5" stroke-dasharray="4 4" opacity="0.75"/>')
    for j in jours:
        suivi, autre = choix.get(j, [0, 0])
        x = _x(j, jmin, jmax) - larg / 2
        y = haut + corps
        for n, couleur in ((autre, AUTRE), (suivi, SUIVI)):
            if not n:
                continue
            h = n / hmax * corps
            y -= h
            a(f'<rect x="{x:.1f}" y="{y:.1f}" width="{larg:.1f}" height="{h:.1f}" '
              f'fill="{couleur}"/>')
    a(f'<line class="rule" x1="{L}" y1="{haut + corps:.1f}" x2="{W - R}" '
      f'y2="{haut + corps:.1f}" stroke-width="1"/>')


def composer(bras: list[tuple[str, dict, dict]], evenement: str, mode_en: str,
             run: str, titre: str, lecture: str) -> str:
    jours = sorted({j for _, choix, tous in bras for j in set(choix) | set(tous)})
    jmin, jmax = jours[0], jours[-1]
    hmax = max(sum(v) for _, choix, _ in bras for v in choix.values())
    pas = (W - L - R) / max(jmax - jmin, 1)
    larg = max(4.0, min(pas * 0.7, 16.0))

    hauteur = T + len(bras) * (CORPS + ECART) - ECART + B
    o: list[str] = []
    a = o.append
    a(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {hauteur}" width="{W}" '
      f'height="{hauteur}" font-family="Inter, Helvetica, Arial, sans-serif" role="img" '
      f'aria-label="Decisions about {mode_en} by day relative to the injected shock">')
    a("<style>"
      ".surface{fill:#fcfcfb}.ink{fill:#1a1a19}.ink2{fill:#5c5b54}.grid{stroke:#e6e5e0}"
      ".rule{stroke:#c9c8c1}"
      "@media (prefers-color-scheme: dark){"
      ".surface{fill:#1a1a19}.ink{fill:#ffffff}.ink2{fill:#c3c2b7}"
      ".grid{stroke:#333330}.rule{stroke:#4a4944}}"
      "</style>")
    a(f'<rect class="surface" width="{W}" height="{hauteur}"/>')
    a(f'<text class="ink" x="{L}" y="27" font-size="17" font-weight="600">{titre}</text>')
    a(f'<text class="ink2" x="{L}" y="47" font-size="12.5">'
      f'Only decisions where {mode_en} was on offer and the model chose: trips with a single '
      f'available itinerary are excluded. Every bar is a count,</text>')
    a(f'<text class="ink2" x="{L}" y="64" font-size="12.5">'
      f'never an average — a day carrying one decision cannot look like a day carrying eight. '
      f'<tspan fill="{SUIVI}" font-weight="600">— {mode_en} chosen</tspan> '
      f'<tspan fill="{AUTRE}" font-weight="600">— another mode</tspan></text>')

    for i, (nom, choix, _tous) in enumerate(bras):
        _bande(a, choix, jours, jmin, jmax, hmax,
               T + i * (CORPS + ECART), CORPS, larg, nom)

    bas = T + (len(bras) - 1) * (CORPS + ECART) + CORPS
    for j in jours:
        if j % 5 == 0 or j == 0:
            a(f'<text class="ink2" x="{_x(j, jmin, jmax):.1f}" y="{bas + 18:.1f}" '
              f'font-size="11" text-anchor="middle">{j:+d}</text>')
    a(f'<text class="ink2" x="{(L + W - R) / 2:.0f}" y="{bas + 38:.1f}" font-size="11.5" '
      f'text-anchor="middle">simulated days relative to the injected shock ({evenement}) · '
      f'weekends are not simulated</text>')
    a(f'<text class="ink2" x="{L}" y="{hauteur - 22:.1f}" font-size="11.5">{lecture}</text>')
    a(f'<text class="ink2" x="{L}" y="{hauteur - 8:.1f}" font-size="10.5">source: {run}</text>')
    a("</svg>")
    return "\n".join(o)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("run", type=Path, help="directory of the TREATED arm (containing moves.csv)")
    p.add_argument("--temoin", type=Path, default=None,
                   help="directory of the control arm, stacked under the treated arm")
    p.add_argument("--mode", default="car", choices=sorted(MODES),
                   help="TRACKED mode, the one the event is supposed to drive away (default: car)")
    p.add_argument("--titre", default=None, help="figure title (English)")
    p.add_argument("--lecture", default="", help="reading sentence, under the figure (English)")
    p.add_argument("-o", "--sortie", type=Path, required=True)
    args = p.parse_args()

    libelle, mode_en = MODES[args.mode]
    evenement = texte_injecte(args.run)
    choix, tous = lire(args.run, libelle)
    total = sum(sum(v) for v in choix.values())
    print(f"  treated: {total} decision(s) where {libelle} was offered, out of "
          f"{sum(tous.values())} decision(s), {len(choix)} day(s) covered")
    if total < DECISIONS_MINIMALES:
        raise SystemExit(f"❌ not conclusive: {total} free decision(s) for a minimum of "
                         f"{DECISIONS_MINIMALES}. This is NOT a null result — it is an "
                         f"absence of measurement, and a hollow figure would read as an absence "
                         f"of effect.")

    bras = [("treated arm", choix, tous)]
    if args.temoin is not None:
        t_choix, t_tous = lire_temoin(args.temoin, libelle, jours_relatifs(args.run))
        t_total = sum(sum(v) for v in t_choix.values())
        print(f"  control: {t_total} decision(s) where {libelle} was offered, out of "
              f"{sum(t_tous.values())} decision(s), {len(t_choix)} day(s) covered")
        if t_total < DECISIONS_MINIMALES:
            raise SystemExit(f"❌ not conclusive: the control arm only carries {t_total} "
                             f"free decision(s). A control too thin allows no "
                             f"comparison, and stacking it would give the opposite illusion.")
        bras.append(("control arm (no shock)", t_choix, t_tous))

    titre = args.titre or f"Decisions about {mode_en} around the injected shock"
    args.sortie.parent.mkdir(parents=True, exist_ok=True)
    args.sortie.write_text(
        composer(bras, evenement, mode_en, str(args.run), titre, args.lecture),
        encoding="utf-8")
    print(f"→ {args.sortie}")

    csv_sortie = args.sortie.with_suffix(".csv")
    with csv_sortie.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["bras", "jour_relatif", "mode_suivi_choisi", "autre_mode_choisi",
                    "decisions_libres", "decisions_du_jour"])
        for nom, ch, to in bras:
            for j in sorted(set(ch) | set(to)):
                suivi, autre = ch.get(j, [0, 0])
                w.writerow([nom, j, suivi, autre, suivi + autre, to.get(j, 0)])
    print(f"→ {csv_sortie}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
